-- GENERATED FILE — do not edit by hand.
-- Source: data/cdcf.json
-- Regenerate: npm run seed:build
--
-- 19 listings. Upserts on slug; votes and moderation status are preserved.

INSERT INTO apis (slug, name, tagline, description, homepage_url, docs_url, repo_url, kind, track, launched_at, platforms, pricing, pricing_note, open_source, license, auth, cors, official, categories, languages, status, deprecated, deprecated_note, source, source_url)
VALUES ('martyrology-api', 'Roman Martyrology API', 'The eulogies of the Roman Martyrology for any liturgical day.', 'Serves the elogia of the Martyrologium Romanum — the short notices read for the saints and blesseds commemorated on each day — keyed to the canonical identifiers in CRMEDR. Built as a companion to the Liturgical Calendar API, so the two answer ''what is celebrated today'' and ''what does the Martyrology say about it'' with the same identifiers. The copyrighted edition texts stay in a private repository; what is public is the API and the identifier scheme.', 'https://github.com/CatholicOS/martyrology-api', NULL, 'https://github.com/CatholicOS/martyrology-api', 'api', 'api', NULL, '[]', 'free', 'Open source; self-hosted or run from the repository.', 1, 'Apache-2.0', 'unknown', 'unknown', 1, '["Saints","Liturgical Calendar"]', '["la","en"]', 'published', 0, NULL, 'Catholic Digital Commons Foundation', 'https://github.com/CatholicOS')
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  tagline = excluded.tagline,
  description = excluded.description,
  homepage_url = excluded.homepage_url,
  docs_url = excluded.docs_url,
  repo_url = excluded.repo_url,
  kind = excluded.kind,
  track = excluded.track,
  launched_at = excluded.launched_at,
  platforms = excluded.platforms,
  pricing = excluded.pricing,
  pricing_note = excluded.pricing_note,
  open_source = excluded.open_source,
  license = excluded.license,
  auth = excluded.auth,
  cors = excluded.cors,
  official = excluded.official,
  categories = excluded.categories,
  languages = excluded.languages,
  deprecated = excluded.deprecated,
  deprecated_note = excluded.deprecated_note,
  source = excluded.source,
  source_url = excluded.source_url,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now');

INSERT INTO apis (slug, name, tagline, description, homepage_url, docs_url, repo_url, kind, track, launched_at, platforms, pricing, pricing_note, open_source, license, auth, cors, official, categories, languages, status, deprecated, deprecated_note, source, source_url)
VALUES ('liturgical-calendar-mcp', 'Liturgical Calendar MCP Server', 'Lets an AI agent query the Roman Catholic liturgical calendar.', 'A Model Context Protocol server in front of the Liturgical Calendar API, exposing liturgical dates, seasons, feasts, saints and rankings as a structured toolset for any MCP client — so an assistant can answer ''what colour are the vestments on the third Sunday of Advent 2027?'' by calling a tool instead of guessing, which unaided models reliably do badly.', 'https://github.com/CatholicOS/liturgical-calendar-mcp', NULL, 'https://github.com/CatholicOS/liturgical-calendar-mcp', 'mcp', 'api', NULL, '[]', 'free', 'Open source; self-hosted or run from the repository.', 1, 'Apache-2.0', 'none', 'unknown', 1, '["Liturgical Calendar","AI & Search","Developer Tools"]', '["en"]', 'published', 0, NULL, 'Catholic Digital Commons Foundation', 'https://github.com/CatholicOS')
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  tagline = excluded.tagline,
  description = excluded.description,
  homepage_url = excluded.homepage_url,
  docs_url = excluded.docs_url,
  repo_url = excluded.repo_url,
  kind = excluded.kind,
  track = excluded.track,
  launched_at = excluded.launched_at,
  platforms = excluded.platforms,
  pricing = excluded.pricing,
  pricing_note = excluded.pricing_note,
  open_source = excluded.open_source,
  license = excluded.license,
  auth = excluded.auth,
  cors = excluded.cors,
  official = excluded.official,
  categories = excluded.categories,
  languages = excluded.languages,
  deprecated = excluded.deprecated,
  deprecated_note = excluded.deprecated_note,
  source = excluded.source,
  source_url = excluded.source_url,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now');

INSERT INTO apis (slug, name, tagline, description, homepage_url, docs_url, repo_url, kind, track, launched_at, platforms, pricing, pricing_note, open_source, license, auth, cors, official, categories, languages, status, deprecated, deprecated_note, source, source_url)
VALUES ('ontokit-api', 'OntoKit API', 'Collaborative OWL ontology curation, as a FastAPI service.', 'A Python service for curating OWL ontologies collaboratively, published on PyPI as `ontokit`. It is the machinery behind the foundation''s semantic work rather than a Catholic dataset in itself, but it is the piece you would reuse if you were modelling any structured body of doctrine or church data.', 'https://github.com/CatholicOS/ontokit-api', NULL, 'https://github.com/CatholicOS/ontokit-api', 'api', 'api', NULL, '[]', 'free', 'Open source; self-hosted or run from the repository.', 1, NULL, 'unknown', 'unknown', 1, '["Developer Tools","AI & Search"]', '["en"]', 'published', 0, NULL, 'Catholic Digital Commons Foundation', 'https://github.com/CatholicOS')
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  tagline = excluded.tagline,
  description = excluded.description,
  homepage_url = excluded.homepage_url,
  docs_url = excluded.docs_url,
  repo_url = excluded.repo_url,
  kind = excluded.kind,
  track = excluded.track,
  launched_at = excluded.launched_at,
  platforms = excluded.platforms,
  pricing = excluded.pricing,
  pricing_note = excluded.pricing_note,
  open_source = excluded.open_source,
  license = excluded.license,
  auth = excluded.auth,
  cors = excluded.cors,
  official = excluded.official,
  categories = excluded.categories,
  languages = excluded.languages,
  deprecated = excluded.deprecated,
  deprecated_note = excluded.deprecated_note,
  source = excluded.source,
  source_url = excluded.source_url,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now');

INSERT INTO apis (slug, name, tagline, description, homepage_url, docs_url, repo_url, kind, track, launched_at, platforms, pricing, pricing_note, open_source, license, auth, cors, official, categories, languages, status, deprecated, deprecated_note, source, source_url)
VALUES ('mediawiki-extensions-semanticsearch', 'SemanticSearch for MediaWiki', 'Hybrid keyword and semantic search for MediaWiki — early scaffold.', 'Adds sentence-transformer embeddings alongside CirrusSearch''s BM25 keyword retrieval and rank-fuses the two, using OpenSearch k-NN. Its own README calls the current release a scaffold, so treat it as a project to watch rather than one to deploy — but the approach is the right one for searching a wiki of magisterial texts, where the wording a reader knows is rarely the wording on the page.', 'https://github.com/CatholicOS/mediawiki-extensions-SemanticSearch', NULL, 'https://github.com/CatholicOS/mediawiki-extensions-SemanticSearch', 'library', 'api', NULL, '[]', 'free', 'Open source; self-hosted or run from the repository.', 1, 'GPL-3.0', 'none', 'unknown', 1, '["AI & Search","Developer Tools"]', '["en"]', 'published', 0, NULL, 'Catholic Digital Commons Foundation', 'https://github.com/CatholicOS')
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  tagline = excluded.tagline,
  description = excluded.description,
  homepage_url = excluded.homepage_url,
  docs_url = excluded.docs_url,
  repo_url = excluded.repo_url,
  kind = excluded.kind,
  track = excluded.track,
  launched_at = excluded.launched_at,
  platforms = excluded.platforms,
  pricing = excluded.pricing,
  pricing_note = excluded.pricing_note,
  open_source = excluded.open_source,
  license = excluded.license,
  auth = excluded.auth,
  cors = excluded.cors,
  official = excluded.official,
  categories = excluded.categories,
  languages = excluded.languages,
  deprecated = excluded.deprecated,
  deprecated_note = excluded.deprecated_note,
  source = excluded.source,
  source_url = excluded.source_url,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now');

INSERT INTO apis (slug, name, tagline, description, homepage_url, docs_url, repo_url, kind, track, launched_at, platforms, pricing, pricing_note, open_source, license, auth, cors, official, categories, languages, status, deprecated, deprecated_note, source, source_url)
VALUES ('cecdr', 'CECDR — Ecclesiastical Circumscriptions', 'Canonical IDs for every diocese, eparchy and prelature.', 'The Common Ecclesiastical Circumscription Data Repository: stable identifiers for the circumscriptions of the Catholic Church — Latin dioceses and archdioceses, Eastern eparchies, archeparchies and exarchates, territorial prelatures and abbacies, apostolic vicariates and prefectures, military and personal ordinariates, personal prelatures and missions. If you have ever tried to join two datasets on diocese name, this is the thing that was missing.', 'https://github.com/CatholicOS/cecdr', NULL, 'https://github.com/CatholicOS/cecdr', 'dataset', 'api', NULL, '[]', 'free', 'Open source; self-hosted or run from the repository.', 1, 'Apache-2.0', 'none', 'unknown', 1, '["Church Data"]', '["la","en"]', 'published', 0, NULL, 'Catholic Digital Commons Foundation', 'https://github.com/CatholicOS')
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  tagline = excluded.tagline,
  description = excluded.description,
  homepage_url = excluded.homepage_url,
  docs_url = excluded.docs_url,
  repo_url = excluded.repo_url,
  kind = excluded.kind,
  track = excluded.track,
  launched_at = excluded.launched_at,
  platforms = excluded.platforms,
  pricing = excluded.pricing,
  pricing_note = excluded.pricing_note,
  open_source = excluded.open_source,
  license = excluded.license,
  auth = excluded.auth,
  cors = excluded.cors,
  official = excluded.official,
  categories = excluded.categories,
  languages = excluded.languages,
  deprecated = excluded.deprecated,
  deprecated_note = excluded.deprecated_note,
  source = excluded.source,
  source_url = excluded.source_url,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now');

INSERT INTO apis (slug, name, tagline, description, homepage_url, docs_url, repo_url, kind, track, launched_at, platforms, pricing, pricing_note, open_source, license, auth, cors, official, categories, languages, status, deprecated, deprecated_note, source, source_url)
VALUES ('cesidr', 'CESIDR — Churches sui iuris', 'Canonical IDs for the 24 Churches sui iuris.', 'The Common Ecclesiae Sui Iuris Data Repository: identifiers for the Latin Church and the 23 Eastern Catholic Churches, across the six liturgical traditions — Latin, Byzantine, Alexandrian, Antiochene, Chaldean and Armenian. Small, fixed, and exactly the sort of list every application re-types slightly differently.', 'https://github.com/CatholicOS/cesidr', NULL, 'https://github.com/CatholicOS/cesidr', 'dataset', 'api', NULL, '[]', 'free', 'Open source; self-hosted or run from the repository.', 1, 'Apache-2.0', 'none', 'unknown', 1, '["Church Data"]', '["la","en"]', 'published', 0, NULL, 'Catholic Digital Commons Foundation', 'https://github.com/CatholicOS')
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  tagline = excluded.tagline,
  description = excluded.description,
  homepage_url = excluded.homepage_url,
  docs_url = excluded.docs_url,
  repo_url = excluded.repo_url,
  kind = excluded.kind,
  track = excluded.track,
  launched_at = excluded.launched_at,
  platforms = excluded.platforms,
  pricing = excluded.pricing,
  pricing_note = excluded.pricing_note,
  open_source = excluded.open_source,
  license = excluded.license,
  auth = excluded.auth,
  cors = excluded.cors,
  official = excluded.official,
  categories = excluded.categories,
  languages = excluded.languages,
  deprecated = excluded.deprecated,
  deprecated_note = excluded.deprecated_note,
  source = excluded.source,
  source_url = excluded.source_url,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now');

INSERT INTO apis (slug, name, tagline, description, homepage_url, docs_url, repo_url, kind, track, launched_at, platforms, pricing, pricing_note, open_source, license, auth, cors, official, categories, languages, status, deprecated, deprecated_note, source, source_url)
VALUES ('crpdr', 'CRPDR — Roman Pontiffs', 'Canonical IDs for the popes, from Peter to the reigning pope.', 'The Common Roman Pontiff Data Repository. Papal lists are a classic source of quiet disagreement — regnal numbering, antipopes, disputed dates — so a shared identifier set matters more here than the size of the data suggests.', 'https://github.com/CatholicOS/crpdr', NULL, 'https://github.com/CatholicOS/crpdr', 'dataset', 'api', NULL, '[]', 'free', 'Open source; self-hosted or run from the repository.', 1, 'Apache-2.0', 'none', 'unknown', 1, '["Church Data"]', '["la","en"]', 'published', 0, NULL, 'Catholic Digital Commons Foundation', 'https://github.com/CatholicOS')
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  tagline = excluded.tagline,
  description = excluded.description,
  homepage_url = excluded.homepage_url,
  docs_url = excluded.docs_url,
  repo_url = excluded.repo_url,
  kind = excluded.kind,
  track = excluded.track,
  launched_at = excluded.launched_at,
  platforms = excluded.platforms,
  pricing = excluded.pricing,
  pricing_note = excluded.pricing_note,
  open_source = excluded.open_source,
  license = excluded.license,
  auth = excluded.auth,
  cors = excluded.cors,
  official = excluded.official,
  categories = excluded.categories,
  languages = excluded.languages,
  deprecated = excluded.deprecated,
  deprecated_note = excluded.deprecated_note,
  source = excluded.source,
  source_url = excluded.source_url,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now');

INSERT INTO apis (slug, name, tagline, description, homepage_url, docs_url, repo_url, kind, track, launched_at, platforms, pricing, pricing_note, open_source, license, auth, cors, official, categories, languages, status, deprecated, deprecated_note, source, source_url)
VALUES ('coecdr', 'COECDR — Ecumenical Councils', 'Canonical IDs for the 21 ecumenical councils.', 'The Common Oecumenical Council Data Repository: identifiers for the councils the Catholic Church recognises as ecumenical, from Nicaea I to Vatican II.', 'https://github.com/CatholicOS/coecdr', NULL, 'https://github.com/CatholicOS/coecdr', 'dataset', 'api', NULL, '[]', 'free', 'Open source; self-hosted or run from the repository.', 1, 'Apache-2.0', 'none', 'unknown', 1, '["Church Data"]', '["la","en"]', 'published', 0, NULL, 'Catholic Digital Commons Foundation', 'https://github.com/CatholicOS')
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  tagline = excluded.tagline,
  description = excluded.description,
  homepage_url = excluded.homepage_url,
  docs_url = excluded.docs_url,
  repo_url = excluded.repo_url,
  kind = excluded.kind,
  track = excluded.track,
  launched_at = excluded.launched_at,
  platforms = excluded.platforms,
  pricing = excluded.pricing,
  pricing_note = excluded.pricing_note,
  open_source = excluded.open_source,
  license = excluded.license,
  auth = excluded.auth,
  cors = excluded.cors,
  official = excluded.official,
  categories = excluded.categories,
  languages = excluded.languages,
  deprecated = excluded.deprecated,
  deprecated_note = excluded.deprecated_note,
  source = excluded.source,
  source_url = excluded.source_url,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now');

INSERT INTO apis (slug, name, tagline, description, homepage_url, docs_url, repo_url, kind, track, launched_at, platforms, pricing, pricing_note, open_source, license, auth, cors, official, categories, languages, status, deprecated, deprecated_note, source, source_url)
VALUES ('cdoctdr', 'CDOCTDR — Doctors of the Church', 'Canonical IDs for the 38 Doctors of the Church.', 'The Common Doctors of the Church Data Repository: stable identifiers for the Doctors, from the four great Latin and Greek Fathers to the most recent declarations.', 'https://github.com/CatholicOS/cdoctdr', NULL, 'https://github.com/CatholicOS/cdoctdr', 'dataset', 'api', NULL, '[]', 'free', 'Open source; self-hosted or run from the repository.', 1, 'Apache-2.0', 'none', 'unknown', 1, '["Church Data","Saints"]', '["la","en"]', 'published', 0, NULL, 'Catholic Digital Commons Foundation', 'https://github.com/CatholicOS')
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  tagline = excluded.tagline,
  description = excluded.description,
  homepage_url = excluded.homepage_url,
  docs_url = excluded.docs_url,
  repo_url = excluded.repo_url,
  kind = excluded.kind,
  track = excluded.track,
  launched_at = excluded.launched_at,
  platforms = excluded.platforms,
  pricing = excluded.pricing,
  pricing_note = excluded.pricing_note,
  open_source = excluded.open_source,
  license = excluded.license,
  auth = excluded.auth,
  cors = excluded.cors,
  official = excluded.official,
  categories = excluded.categories,
  languages = excluded.languages,
  deprecated = excluded.deprecated,
  deprecated_note = excluded.deprecated_note,
  source = excluded.source,
  source_url = excluded.source_url,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now');

INSERT INTO apis (slug, name, tagline, description, homepage_url, docs_url, repo_url, kind, track, launched_at, platforms, pricing, pricing_note, open_source, license, auth, cors, official, categories, languages, status, deprecated, deprecated_note, source, source_url)
VALUES ('cmddr', 'CMDDR — Magisterial Documents', 'Canonical IDs for magisterial and papal documents.', 'The Common Magisterial Document Data Repository: identifiers for encyclicals, exhortations, constitutions, papal speeches and homilies, with semantic distinctions between the document types — which is the part that makes citation across projects possible.', 'https://github.com/CatholicOS/cmddr', NULL, 'https://github.com/CatholicOS/cmddr', 'dataset', 'api', NULL, '[]', 'free', 'Open source; self-hosted or run from the repository.', 1, 'Apache-2.0', 'none', 'unknown', 1, '["Church Documents","Church Data"]', '["la","en"]', 'published', 0, NULL, 'Catholic Digital Commons Foundation', 'https://github.com/CatholicOS')
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  tagline = excluded.tagline,
  description = excluded.description,
  homepage_url = excluded.homepage_url,
  docs_url = excluded.docs_url,
  repo_url = excluded.repo_url,
  kind = excluded.kind,
  track = excluded.track,
  launched_at = excluded.launched_at,
  platforms = excluded.platforms,
  pricing = excluded.pricing,
  pricing_note = excluded.pricing_note,
  open_source = excluded.open_source,
  license = excluded.license,
  auth = excluded.auth,
  cors = excluded.cors,
  official = excluded.official,
  categories = excluded.categories,
  languages = excluded.languages,
  deprecated = excluded.deprecated,
  deprecated_note = excluded.deprecated_note,
  source = excluded.source,
  source_url = excluded.source_url,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now');

INSERT INTO apis (slug, name, tagline, description, homepage_url, docs_url, repo_url, kind, track, launched_at, platforms, pricing, pricing_note, open_source, license, auth, cors, official, categories, languages, status, deprecated, deprecated_note, source, source_url)
VALUES ('clbdr', 'CLBDR — Liturgical Books', 'Canonical IDs for the liturgical books of the Roman Rite and their editions.', 'The Common Liturgical Books Data Repository: each book — Missal, Lectionary, Liturgy of the Hours, Martyrology, the Pontifical and Ritual ordines, the Book of Blessings, the Ceremonial of Bishops — as a book identity, with its Latin typical editions and approved vernacular editions underneath. Supersedes the per-book registries the foundation started with.', 'https://github.com/CatholicOS/clbdr', NULL, 'https://github.com/CatholicOS/clbdr', 'dataset', 'api', NULL, '[]', 'free', 'Open source; self-hosted or run from the repository.', 1, 'Apache-2.0', 'none', 'unknown', 1, '["Liturgy","Church Data"]', '["la","en"]', 'published', 0, NULL, 'Catholic Digital Commons Foundation', 'https://github.com/CatholicOS')
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  tagline = excluded.tagline,
  description = excluded.description,
  homepage_url = excluded.homepage_url,
  docs_url = excluded.docs_url,
  repo_url = excluded.repo_url,
  kind = excluded.kind,
  track = excluded.track,
  launched_at = excluded.launched_at,
  platforms = excluded.platforms,
  pricing = excluded.pricing,
  pricing_note = excluded.pricing_note,
  open_source = excluded.open_source,
  license = excluded.license,
  auth = excluded.auth,
  cors = excluded.cors,
  official = excluded.official,
  categories = excluded.categories,
  languages = excluded.languages,
  deprecated = excluded.deprecated,
  deprecated_note = excluded.deprecated_note,
  source = excluded.source,
  source_url = excluded.source_url,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now');

INSERT INTO apis (slug, name, tagline, description, homepage_url, docs_url, repo_url, kind, track, launched_at, platforms, pricing, pricing_note, open_source, license, auth, cors, official, categories, languages, status, deprecated, deprecated_note, source, source_url)
VALUES ('cledr', 'CLEDR — Liturgical Events', 'Canonical IDs for the celebrations of the Roman Missal.', 'The Common Liturgical Events Data Repository: identifiers for the celebrations defined by the Roman Missal editio typica, across both the Temporale and the Sanctorale. The natural key to join a calendar API to a lectionary, a martyrology or a set of propers.', 'https://github.com/CatholicOS/cledr', NULL, 'https://github.com/CatholicOS/cledr', 'dataset', 'api', NULL, '[]', 'free', 'Open source; self-hosted or run from the repository.', 1, 'Apache-2.0', 'none', 'unknown', 1, '["Liturgical Calendar","Church Data"]', '["la","en"]', 'published', 0, NULL, 'Catholic Digital Commons Foundation', 'https://github.com/CatholicOS')
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  tagline = excluded.tagline,
  description = excluded.description,
  homepage_url = excluded.homepage_url,
  docs_url = excluded.docs_url,
  repo_url = excluded.repo_url,
  kind = excluded.kind,
  track = excluded.track,
  launched_at = excluded.launched_at,
  platforms = excluded.platforms,
  pricing = excluded.pricing,
  pricing_note = excluded.pricing_note,
  open_source = excluded.open_source,
  license = excluded.license,
  auth = excluded.auth,
  cors = excluded.cors,
  official = excluded.official,
  categories = excluded.categories,
  languages = excluded.languages,
  deprecated = excluded.deprecated,
  deprecated_note = excluded.deprecated_note,
  source = excluded.source,
  source_url = excluded.source_url,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now');

INSERT INTO apis (slug, name, tagline, description, homepage_url, docs_url, repo_url, kind, track, launched_at, platforms, pricing, pricing_note, open_source, license, auth, cors, official, categories, languages, status, deprecated, deprecated_note, source, source_url)
VALUES ('crmedr', 'CRMEDR — Martyrology Eulogies', 'Canonical IDs for the eulogies of the Roman Martyrology.', 'The Common Roman Martyrology Eulogy Data Repository: identifiers for the elogia of the Martyrologium Romanum, and thereby for the saints, blesseds and commemorations they are addressed to. The registry is public; the copyrighted edition texts are not.', 'https://github.com/CatholicOS/crmedr', NULL, 'https://github.com/CatholicOS/crmedr', 'dataset', 'api', NULL, '[]', 'free', 'Open source; self-hosted or run from the repository.', 1, 'Apache-2.0', 'none', 'unknown', 1, '["Saints","Church Data"]', '["la","en"]', 'published', 0, NULL, 'Catholic Digital Commons Foundation', 'https://github.com/CatholicOS')
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  tagline = excluded.tagline,
  description = excluded.description,
  homepage_url = excluded.homepage_url,
  docs_url = excluded.docs_url,
  repo_url = excluded.repo_url,
  kind = excluded.kind,
  track = excluded.track,
  launched_at = excluded.launched_at,
  platforms = excluded.platforms,
  pricing = excluded.pricing,
  pricing_note = excluded.pricing_note,
  open_source = excluded.open_source,
  license = excluded.license,
  auth = excluded.auth,
  cors = excluded.cors,
  official = excluded.official,
  categories = excluded.categories,
  languages = excluded.languages,
  deprecated = excluded.deprecated,
  deprecated_note = excluded.deprecated_note,
  source = excluded.source,
  source_url = excluded.source_url,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now');

INSERT INTO apis (slug, name, tagline, description, homepage_url, docs_url, repo_url, kind, track, launched_at, platforms, pricing, pricing_note, open_source, license, auth, cors, official, categories, languages, status, deprecated, deprecated_note, source, source_url)
VALUES ('ciclsaldr', 'CICLSALDR — Consecrated Life', 'Canonical IDs for religious orders, congregations and societies.', 'The Common Institutes of Consecrated Life and Societies of Apostolic Life Data Repository: identifiers for religious and monastic orders, congregations, secular institutes and societies of apostolic life, grouped into the religious families they belong to.', 'https://github.com/CatholicOS/ciclsaldr', NULL, 'https://github.com/CatholicOS/ciclsaldr', 'dataset', 'api', NULL, '[]', 'free', 'Open source; self-hosted or run from the repository.', 1, 'Apache-2.0', 'none', 'unknown', 1, '["Church Data"]', '["la","en"]', 'published', 0, NULL, 'Catholic Digital Commons Foundation', 'https://github.com/CatholicOS')
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  tagline = excluded.tagline,
  description = excluded.description,
  homepage_url = excluded.homepage_url,
  docs_url = excluded.docs_url,
  repo_url = excluded.repo_url,
  kind = excluded.kind,
  track = excluded.track,
  launched_at = excluded.launched_at,
  platforms = excluded.platforms,
  pricing = excluded.pricing,
  pricing_note = excluded.pricing_note,
  open_source = excluded.open_source,
  license = excluded.license,
  auth = excluded.auth,
  cors = excluded.cors,
  official = excluded.official,
  categories = excluded.categories,
  languages = excluded.languages,
  deprecated = excluded.deprecated,
  deprecated_note = excluded.deprecated_note,
  source = excluded.source,
  source_url = excluded.source_url,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now');

INSERT INTO apis (slug, name, tagline, description, homepage_url, docs_url, repo_url, kind, track, launched_at, platforms, pricing, pricing_note, open_source, license, auth, cors, official, categories, languages, status, deprecated, deprecated_note, source, source_url)
VALUES ('ontology-semantic-canon', 'Catholic Semantic Canon', 'A formal ontology of Scripture, Tradition and the Magisterium.', 'Models the Deposit of Faith as a machine-readable structure: not a bibliography but a map of how the sources relate in authority, chronology and theological weight. The formal backbone the identifier registries hang from.', 'https://github.com/CatholicOS/ontology-semantic-canon', NULL, 'https://github.com/CatholicOS/ontology-semantic-canon', 'dataset', 'api', NULL, '[]', 'free', 'Open source; self-hosted or run from the repository.', 1, 'Apache-2.0', 'none', 'unknown', 1, '["Catechism & Doctrine","Church Data"]', '["la","en"]', 'published', 0, NULL, 'Catholic Digital Commons Foundation', 'https://github.com/CatholicOS')
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  tagline = excluded.tagline,
  description = excluded.description,
  homepage_url = excluded.homepage_url,
  docs_url = excluded.docs_url,
  repo_url = excluded.repo_url,
  kind = excluded.kind,
  track = excluded.track,
  launched_at = excluded.launched_at,
  platforms = excluded.platforms,
  pricing = excluded.pricing,
  pricing_note = excluded.pricing_note,
  open_source = excluded.open_source,
  license = excluded.license,
  auth = excluded.auth,
  cors = excluded.cors,
  official = excluded.official,
  categories = excluded.categories,
  languages = excluded.languages,
  deprecated = excluded.deprecated,
  deprecated_note = excluded.deprecated_note,
  source = excluded.source,
  source_url = excluded.source_url,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now');

INSERT INTO apis (slug, name, tagline, description, homepage_url, docs_url, repo_url, kind, track, launched_at, platforms, pricing, pricing_note, open_source, license, auth, cors, official, categories, languages, status, deprecated, deprecated_note, source, source_url)
VALUES ('crmetdr', 'CRMETDR — Roman Missal Editions', 'Canonical IDs for the editions of the Latin Roman Missal.', 'Proposed identifiers for the Missal edition line, 1474–2008. Its work was carried into the CLBDR, which covers every liturgical book of the Roman Rite rather than one, and this repository was archived.', 'https://github.com/CatholicOS/crmetdr', NULL, 'https://github.com/CatholicOS/crmetdr', 'dataset', 'api', NULL, '[]', 'free', 'Open source; self-hosted or run from the repository.', 1, 'Apache-2.0', 'none', 'unknown', 1, '["Liturgy","Church Data"]', '["la","en"]', 'published', 1, 'Archived by its maintainers and absorbed into CLBDR, the Common Liturgical Books Data Repository, which covers all the books of the Roman Rite. Use CLBDR for new work; everything here was carried over.', 'Catholic Digital Commons Foundation', 'https://github.com/CatholicOS')
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  tagline = excluded.tagline,
  description = excluded.description,
  homepage_url = excluded.homepage_url,
  docs_url = excluded.docs_url,
  repo_url = excluded.repo_url,
  kind = excluded.kind,
  track = excluded.track,
  launched_at = excluded.launched_at,
  platforms = excluded.platforms,
  pricing = excluded.pricing,
  pricing_note = excluded.pricing_note,
  open_source = excluded.open_source,
  license = excluded.license,
  auth = excluded.auth,
  cors = excluded.cors,
  official = excluded.official,
  categories = excluded.categories,
  languages = excluded.languages,
  deprecated = excluded.deprecated,
  deprecated_note = excluded.deprecated_note,
  source = excluded.source,
  source_url = excluded.source_url,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now');

INSERT INTO apis (slug, name, tagline, description, homepage_url, docs_url, repo_url, kind, track, launched_at, platforms, pricing, pricing_note, open_source, license, auth, cors, official, categories, languages, status, deprecated, deprecated_note, source, source_url)
VALUES ('outwardsign', 'Outward Sign', 'Plan, communicate and celebrate sacraments in a parish.', 'A sacrament and sacramental management tool for Catholic parishes: preparing, scheduling and running baptisms, marriages, confirmations and the rest, with the paperwork and the people kept in one place. Free and open source, aimed at parishes that cannot buy a diocesan platform.', 'https://github.com/CatholicOS/outwardsign', NULL, 'https://github.com/CatholicOS/outwardsign', 'api', 'product', NULL, '["web","parish"]', 'free', 'Open source; self-hosted or run from the repository.', 1, NULL, 'none', 'unknown', 1, '["Parish Tools"]', '["en"]', 'published', 0, NULL, 'Catholic Digital Commons Foundation', 'https://github.com/CatholicOS')
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  tagline = excluded.tagline,
  description = excluded.description,
  homepage_url = excluded.homepage_url,
  docs_url = excluded.docs_url,
  repo_url = excluded.repo_url,
  kind = excluded.kind,
  track = excluded.track,
  launched_at = excluded.launched_at,
  platforms = excluded.platforms,
  pricing = excluded.pricing,
  pricing_note = excluded.pricing_note,
  open_source = excluded.open_source,
  license = excluded.license,
  auth = excluded.auth,
  cors = excluded.cors,
  official = excluded.official,
  categories = excluded.categories,
  languages = excluded.languages,
  deprecated = excluded.deprecated,
  deprecated_note = excluded.deprecated_note,
  source = excluded.source,
  source_url = excluded.source_url,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now');

INSERT INTO apis (slug, name, tagline, description, homepage_url, docs_url, repo_url, kind, track, launched_at, platforms, pricing, pricing_note, open_source, license, auth, cors, official, categories, languages, status, deprecated, deprecated_note, source, source_url)
VALUES ('ontokit-web', 'OntoKit Web', 'Browser front end for collaborative ontology curation.', 'The Next.js interface to the OntoKit API — where the curation of the foundation''s ontologies actually happens. Of interest mainly if you are contributing to that work rather than consuming it.', 'https://github.com/CatholicOS/ontokit-web', NULL, 'https://github.com/CatholicOS/ontokit-web', 'api', 'product', NULL, '["web"]', 'free', 'Open source; self-hosted or run from the repository.', 1, NULL, 'none', 'unknown', 1, '["Developer Tools","Church Data"]', '["en"]', 'published', 0, NULL, 'Catholic Digital Commons Foundation', 'https://github.com/CatholicOS')
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  tagline = excluded.tagline,
  description = excluded.description,
  homepage_url = excluded.homepage_url,
  docs_url = excluded.docs_url,
  repo_url = excluded.repo_url,
  kind = excluded.kind,
  track = excluded.track,
  launched_at = excluded.launched_at,
  platforms = excluded.platforms,
  pricing = excluded.pricing,
  pricing_note = excluded.pricing_note,
  open_source = excluded.open_source,
  license = excluded.license,
  auth = excluded.auth,
  cors = excluded.cors,
  official = excluded.official,
  categories = excluded.categories,
  languages = excluded.languages,
  deprecated = excluded.deprecated,
  deprecated_note = excluded.deprecated_note,
  source = excluded.source,
  source_url = excluded.source_url,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now');

INSERT INTO apis (slug, name, tagline, description, homepage_url, docs_url, repo_url, kind, track, launched_at, platforms, pricing, pricing_note, open_source, license, auth, cors, official, categories, languages, status, deprecated, deprecated_note, source, source_url)
VALUES ('martyrology-frontend', 'Martyrology Curation Frontend', 'Review tool for the Roman Martyrology identifier pipeline.', 'Lets a curator compare how a canonical eulogy ID is placed across Martyrology editions and accept, reject or edit proposed corrections against the live text. It holds no copyrighted text itself — everything it shows comes from the public CRMEDR registry or the API at request time.', 'https://github.com/CatholicOS/martyrology-frontend', NULL, 'https://github.com/CatholicOS/martyrology-frontend', 'api', 'product', NULL, '["web"]', 'free', 'Open source; self-hosted or run from the repository.', 1, NULL, 'none', 'unknown', 1, '["Church Data"]', '["la","en"]', 'published', 0, NULL, 'Catholic Digital Commons Foundation', 'https://github.com/CatholicOS')
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  tagline = excluded.tagline,
  description = excluded.description,
  homepage_url = excluded.homepage_url,
  docs_url = excluded.docs_url,
  repo_url = excluded.repo_url,
  kind = excluded.kind,
  track = excluded.track,
  launched_at = excluded.launched_at,
  platforms = excluded.platforms,
  pricing = excluded.pricing,
  pricing_note = excluded.pricing_note,
  open_source = excluded.open_source,
  license = excluded.license,
  auth = excluded.auth,
  cors = excluded.cors,
  official = excluded.official,
  categories = excluded.categories,
  languages = excluded.languages,
  deprecated = excluded.deprecated,
  deprecated_note = excluded.deprecated_note,
  source = excluded.source,
  source_url = excluded.source_url,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now');
